apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Values.image.name }}"
  labels:
    app: {{ .Values.image.name }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.image.name }}
    release: {{ .Release.Name }}